_wandb:
    value:
        cli_version: 0.23.1
        e:
            vjquc3i5yjw8fxo21ps5cadqcuj91f5a:
                args:
                    - --config
                    - configs/default.yaml
                    - --epochs
                    - "20"
                codePath: fsbed/scripts/train_baseline.py
                codePathLocal: scripts/train_baseline.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "83955703808"
                        used: "75659923456"
                email: aldo-sula@outlook.com
                executable: /data/msc-proj/sppc18_venv/bin/python
                git:
                    commit: c23ced9ca14fdf1ef582ae754e37c1897a266f7e
                    remote: git@github.com:aldosula/DSAI_Project.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-36fe3ea7-760f-6260-1d5c-11f04080ad1b
                host: sppc18
                memory:
                    total: "33329668096"
                os: Linux-6.1.0-41-amd64-x86_64-with-glibc2.36
                program: /export/home/4sula/DSAI_Final_Project/DSAI_Project/fsbed/scripts/train_baseline.py
                python: CPython 3.11.2
                root: /export/home/4sula/DSAI_Final_Project/DSAI_Project/fsbed
                startedAt: "2026-01-18T15:23:07.312937Z"
                writerId: vjquc3i5yjw8fxo21ps5cadqcuj91f5a
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
embed_dim:
    value: 1024
epochs:
    value: 20
feature_type:
    value: logmel
lr:
    value: 0.0003
mixup_alpha:
    value: 0.4
use_mixup:
    value: true
